site_name: API Clients Encom
nav:
  - Home: index.md
  - API SMS:
      - 'Messages unitaires': sms-messages-unitaires.md
      - 'Listes de diffusions': sms-listes-de-diffusion.md
theme:
  name: material
  custom_dir: overrides
